# This is the main Actions configuration: Maven testing

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # test workflow copied from tablesaw to ensure consistency
  test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        # Test the Java LTS versions and latest version available
        java-version: [8, 11, 16]
        os: [macOS-latest, ubuntu-latest, windows-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK $
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      - name: Install Hadoop on Windows
        if: ${{runner.os == 'Windows'}}
        run: choco install hadoop --version=2.9.0
      - name: Test with Maven
        run: mvn test

